train_file: data/ag_news/train_modified.csv
test_file: data/ag_news/test_modified.csv
embedding_source: pre-trained/embeddings/glove/glove.840B.300d.txt # char_one_hot
batch_size: 8
seq_len: # 300
epochs: 16
model: attention_rnn
seed: 313

